Repository EngenheirosDoHavaii/EngDSoft, pull requests merged in 2023-06, with the labels that each got.

#48 Add Itens to Firestore Database
  package-lock.json
  src/components/Modal/AddItemModal.tsx
  src/entity/item-entity.ts
  src/services/firebase.ts
Labels: [E2]

#50 Feature/architecture review
  README.md
Labels: Avaliacao A4.1

#65 Fix Code Smell: Duplicate code
  src/components/Modal/AddItemModal.tsx
  src/entity/item-entity.ts
  src/services/firebase.ts
Labels: Avaliacao A4.2

#66 Singleton pattern implementation
  src/components/Modal/AddItemModal.tsx
  src/components/ProductView.tsx
  src/components/Protected.tsx
  src/components/UserProductsList/UserProductList.tsx
  src/pages/Product List/ProductListView.tsx
  src/pages/Profile/Profile.tsx
  src/pages/SignIn/SignIn.tsx
  src/services/firebase.ts
Labels: Avaliacao A4.1
